# Generated by Django 2.0 on 2022-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='adscription_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
