# Generated by Django 2.0 on 2022-12-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_adscription_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='adscription_center',
            field=models.CharField(blank=True, default='Universidad de Sevilla', max_length=100, null=True),
        ),
    ]
