language: python 
python: 
- "3.6"
- "3.3"
- "2.7"
services:
- postgresql
env: 
- DJANGO_VERSION=2.0 DB=postgres
- DJANGO_VERSION=1.10.8 DB=postgres
- DJANGO_VERSION=1.11.5 DB=postgres
global:
  - PGPORT=5432
before_install: 
- cd decide
install: 
- pip install -q Django==$DJANGO_VERSION
- pip install -r ../requirements.txt
before_script: 
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py migrate
script: 
- python manage.py test
addons:
  postgresql: "9.6"
notifications:
  email:
    recipients:
      - mcarmenjara@gmail.com
      - carjaralv@alum.us.es
    on_success: always # default: change
    on_failure: always # default: always


