language: python 
python: 
- 3.6
sudo: required
addons:
  postgresql: "9.6"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script: 
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python3 ./decide/manage.py makemigrations
- python3 ./decide/manage.py migrate
script: 
- python3 ./decide/manage.py test


