# Generated by Django 2.0 on 2022-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
