# Generated by Django 2.0 on 2021-01-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('leader', models.CharField(max_length=200)),
                ('president', models.CharField(blank=True, max_length=151, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YesOrNoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('choice', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='url',
            field=models.CharField(help_text='http://localhost:8000/booth/', max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='politicalparty',
            unique_together={('name', 'acronym', 'leader')},
        ),
        migrations.AddField(
            model_name='voting',
            name='political_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.PoliticalParty'),
        ),
    ]
