# Generated by Django 2.0 on 2022-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
