# Generated by Django 2.0 on 2022-01-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20220103_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvoting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_voting', to='census.ParentGroup'),
        ),
    ]
