# Generated by Django 2.0 on 2021-01-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210106_2332'),
        ('voting', '0004_auto_20210115_1139'),
    ]

    operations = [
    ]
