BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXX XXX
        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX

        XXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXX XX X XX XXXXXXXXXXX XXXXXXX

            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
            XXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXX
                        XXXX
                            XXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXXX
                        XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXXXXX
                XXXXXXXX
            XXXXXX

        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
    XXXX XXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
        XXX XXXXXX X FFFFX
        XXX XXX X XXX XXXXX
            XXXXXXXXXXX XXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXXX
            XXXXX X
                XXXXXXX XXXXXX
            X
        XX
    XXXXXXXXX
XXXXXXX
BBBBBBBB
