XXXXXXXXX XXXXX
XXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXX XX
        XXXXXXXBBBBB BBBBBXXXXXXXBBBBBBBBXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBB
    XXXXXXX
    XXXXXX
        BBBBB BBBBBBB
        BBBBBBBB

        BBBBB BBBBBBBBBBBBBBBBB
    XXXXXXX
XXXXXXX
